### ISSUE TITLE
Taskbar size is shorter than actual on 22H2 Inssider Preview or 23H2?

### ISSUE THREAD

**Issue by Gniang** [Gniang/RoundedTB#2]
Seems like a Windows spec change.

**Comment by hakuno2000** [comment]
Thanks for your fork, now it works on build 22621.2361
![image](https://github.com/Gniang/RoundedTB/assets/35840771/2841c497-bd44-4331-bef7-9d0f7fd55fc6)

**Comment by farazfarid** [comment]
@hakuno2000 which settings did you apply? Because no matter which settings I do it's still not working on my end

**Comment by thedanamo** [comment]
I cannot get the .exe to run either. Just does nothing when I try to run it.

**Comment by rodrigosomoza** [comment]
Hello, same here after yesterday update. The taskbar is not showing all the icons. Can someone, that made the latest windows update, drop here his config file pls?

**Comment by MazinLabib10** [comment]
I had the same issue after the latest update. The workaround I found is to try out some negative values for inner margin until you find one that fits.

**Comment by iokinai** [comment]
I made this fix in a hurry, so it may contain errors, sorry. The main problem is that in new versions of Windows (as I understand it), taskbar.AppListRect.Right stores not the right border of the application bar, but its center (and there is also some strange offset there, perhaps a Windows bug), so replacing
centredDistanceFromEdge = taskbar.TaskbarRect.Right - taskbar.AppListRect.Right - Convert.ToInt32(2 * taskbar.ScaleFactor); on
centredDistanceFromEdge = taskbar.TaskbarRect.Right - taskbar.AppListRect.Right + (taskbar.AppListRect.Right - taskbar.AppListRect.Left) - Convert.ToInt32(2 * taskbar.ScaleFactor);
in Taskbar.cs:247
and
mainRegion = LocalPInvoke.CreateRoundRectRgn(
                         centredDistanceFromEdge + centredEffectiveRegion.Left,
                         centeredEffectiveRegion.Top,
                         centredEffectiveRegion.Width - centredDistanceFromEdge,
                         centeredEffectiveRegion.Height,
                         centeredEffectiveRegion.CornerRadius,
                         centredEffectiveRegion.CornerRadius
                         );
on

mainRegion = LocalPInvoke.CreateRoundRectRgn(
                         centredDistanceFromEdge + centredEffectiveRegion.Left + 48,
                         centeredEffectiveRegion.Top,
                         centredEffectiveRegion.Width - centredDistanceFromEdge - 48,
                         centeredEffectiveRegion.Height,
                         centeredEffectiveRegion.CornerRadius,
                         centredEffectiveRegion.CornerRadius
                         );
in Taskbar.cs:258 helped solve the problem
  
Here is the fixed release (works fine for me): https://drive.google.com/file/d/1XcehRMJkOrvNzEgGuSMTKtZ4bxm9tG-B/view?usp=sharing

**Comment by ricardo119** [comment]
I founded the solution and it's pretty simple.

The issue with the icons don't appear can be fixed by editing the RoundedTB inner margin super long so that doesn't happen. Normal  is the solution that people comment more but the opaque part of the task bar will not be dynamic and still be super long when you don't have enough icons to fill.

![Screenshot 2023-10-12 194510](https://github.com/Gniang/RoundedTB/assets/64024735/eb268c20-67e5-42f7-9237-91173f354ed7)

The problem with that solution before is the opaque default taskbar so if you make the taskbar transparent you will not see it and you will never know if the RoundedTB is working as before. So, the same people that made the RoundedTB also made TranslucentTB and fixes the issue instantly.

This solution is not the best if you want to keep the opaque taskbar but I think that if you already had the work to make it rounded why not make it transparent? 

Personally my solution fixed my problem and I think nobody have ever share this tip. If you want to keep the "default" taskbar this solution will not work unfortunately.


![Screenshot 2023-10-12 194526](https://github.com/Gniang/RoundedTB/assets/64024735/bdc5fff4-14a2-491f-801b-f2437526aef1)

**Comment by MazinLabib10** [comment]
> I made this fix in a hurry, so it may contain errors, sorry. The main problem is that in new versions of Windows (as I understand it), taskbar.AppListRect.Right stores not the right border of the application bar, but its center (and there is also some strange offset there, perhaps a Windows bug), so replacing centredDistanceFromEdge = taskbar.TaskbarRect.Right - taskbar.AppListRect.Right - Convert.ToInt32(2 * taskbar.ScaleFactor); on centredDistanceFromEdge = taskbar.TaskbarRect.Right - taskbar.AppListRect.Right + (taskbar.AppListRect.Right - taskbar.AppListRect.Left) - Convert.ToInt32(2 * taskbar.ScaleFactor); in Taskbar.cs:247 and mainRegion = LocalPInvoke.CreateRoundRectRgn( centredDistanceFromEdge + centredEffectiveRegion.Left, centeredEffectiveRegion.Top, centredEffectiveRegion.Width - centredDistanceFromEdge, centeredEffectiveRegion.Height, centeredEffectiveRegion.CornerRadius, centredEffectiveRegion.CornerRadius ); on
> 
> mainRegion = LocalPInvoke.CreateRoundRectRgn( centredDistanceFromEdge + centredEffectiveRegion.Left + 48, centeredEffectiveRegion.Top, centredEffectiveRegion.Width - centredDistanceFromEdge - 48, centeredEffectiveRegion.Height, centeredEffectiveRegion.CornerRadius, centredEffectiveRegion.CornerRadius ); in Taskbar.cs:258 helped solve the problem
> 
> Here is the fixed release (works fine for me): https://drive.google.com/file/d/1XcehRMJkOrvNzEgGuSMTKtZ4bxm9tG-B/view?usp=sharing
> 
> upd. if it crashes on startup please remove the file C:\Users(your username)\AppData\Local\rtb.json

So, I tried your version of the app and, although I had to modify the margin settings to show all the icons, it was working fine. But after a few minutes, it stopped working and the default taskbar showed up. When I right-clicked on the icon in the notification tray, it crashed completely. I have to manually restart it and yet the same happens again after a few minutes. Any fix for it?

**Comment by YuhGnad** [comment]
I had same issue here. But none of them work in my case. I don't know what to do. Sorry but I don't understand anything of what @Gniang commented. My bad. Sorry again!

**Comment by YuhGnad** [comment]
> I had same issue here. But none of them work in my case. I don't know what to do. Sorry but I don't understand anything of what @Gniang commented. My bad. Sorry again!

P/s: My laptop currently run on stable version of windows 11

**Comment by ricardo119** [comment]
> > I made this fix in a hurry, so it may contain errors, sorry. The main problem is that in new versions of Windows (as I understand it), taskbar.AppListRect.Right stores not the right border of the application bar, but its center (and there is also some strange offset there, perhaps a Windows bug), so replacing centredDistanceFromEdge = taskbar.TaskbarRect.Right - taskbar.AppListRect.Right - Convert.ToInt32(2 * taskbar.ScaleFactor); on centredDistanceFromEdge = taskbar.TaskbarRect.Right - taskbar.AppListRect.Right + (taskbar.AppListRect.Right - taskbar.AppListRect.Left) - Convert.ToInt32(2 * taskbar.ScaleFactor); in Taskbar.cs:247 and mainRegion = LocalPInvoke.CreateRoundRectRgn( centredDistanceFromEdge + centredEffectiveRegion.Left, centeredEffectiveRegion.Top, centredEffectiveRegion.Width - centredDistanceFromEdge, centeredEffectiveRegion.Height, centeredEffectiveRegion.CornerRadius, centredEffectiveRegion.CornerRadius ); on
> > mainRegion = LocalPInvoke.CreateRoundRectRgn( centredDistanceFromEdge + centredEffectiveRegion.Left + 48, centeredEffectiveRegion.Top, centredEffectiveRegion.Width - centredDistanceFromEdge - 48, centeredEffectiveRegion.Height, centeredEffectiveRegion.CornerRadius, centredEffectiveRegion.CornerRadius ); in Taskbar.cs:258 helped solve the problem
> > Here is the fixed release (works fine for me): https://drive.google.com/file/d/1XcehRMJkOrvNzEgGuSMTKtZ4bxm9tG-B/view?usp=sharing
> > upd. if it crashes on startup please remove the file C:\Users(your username)\AppData\Local\rtb.json
> 
> So, I tried your version of the app and, although I had to modify the margin settings to show all the icons, it was working fine. But after a few minutes, it stopped working and the default taskbar showed up. When I right-clicked on the icon in the notification tray, it crashed completely. I have to manually restart it and yet the same happens again after a few minutes. Any fix for it?

I had the same issue and I just reinstall the roundedTB and also my rainmeter was full of unnecessary mods that made everything crashes. Just try to reinstal and see if the roudedTB is not eating your RAM and maybe check if you can make less RAM intensive...

**Comment by MazinLabib10** [comment]
> > > I made this fix in a hurry, so it may contain errors, sorry. The main problem is that in new versions of Windows (as I understand it), taskbar.AppListRect.Right stores not the right border of the application bar, but its center (and there is also some strange offset there, perhaps a Windows bug), so replacing centredDistanceFromEdge = taskbar.TaskbarRect.Right - taskbar.AppListRect.Right - Convert.ToInt32(2 * taskbar.ScaleFactor); on centredDistanceFromEdge = taskbar.TaskbarRect.Right - taskbar.AppListRect.Right + (taskbar.AppListRect.Right - taskbar.AppListRect.Left) - Convert.ToInt32(2 * taskbar.ScaleFactor); in Taskbar.cs:247 and mainRegion = LocalPInvoke.CreateRoundRectRgn( centredDistanceFromEdge + centredEffectiveRegion.Left, centeredEffectiveRegion.Top, centredEffectiveRegion.Width - centredDistanceFromEdge, centeredEffectiveRegion.Height, centeredEffectiveRegion.CornerRadius, centredEffectiveRegion.CornerRadius ); on
> > > mainRegion = LocalPInvoke.CreateRoundRectRgn( centredDistanceFromEdge + centredEffectiveRegion.Left + 48, centeredEffectiveRegion.Top, centredEffectiveRegion.Width - centredDistanceFromEdge - 48, centeredEffectiveRegion.Height, centeredEffectiveRegion.CornerRadius, centredEffectiveRegion.CornerRadius ); in Taskbar.cs:258 helped solve the problem
> > > Here is the fixed release (works fine for me): https://drive.google.com/file/d/1XcehRMJkOrvNzEgGuSMTKtZ4bxm9tG-B/view?usp=sharing
> > > upd. if it crashes on startup please remove the file C:\Users(your username)\AppData\Local\rtb.json
> > 
> > 
> > So, I tried your version of the app and, although I had to modify the margin settings to show all the icons, it was working fine. But after a few minutes, it stopped working and the default taskbar showed up. When I right-clicked on the icon in the notification tray, it crashed completely. I have to manually restart it and yet the same happens again after a few minutes. Any fix for it?
> 
> I had the same issue and I just reinstall the roundedTB and also my rainmeter was full of unnecessary mods that made everything crashes. Just try to reinstal and see if the roudedTB is not eating your RAM and maybe check if you can make less RAM intensive...

Actually, I installed the new update and it works absolutely fine. So don't have any issues now.

**Comment by twix0r25** [comment]
not working on 
![image](https://github.com/Gniang/RoundedTB/assets/150279014/2c59bb5b-8490-4218-bbcd-5f88aa4f3bcd)

**Comment by sb-arnav** [comment]
Well, I don't know how to fix it, but until there is no legit way, you all can change these things to be hidden, and it will work fine without them.
![image](https://github.com/Gniang/RoundedTB/assets/116789409/a5fc5078-f459-46e5-90c9-9ddc8d76231a)

**Comment by AnonymousID5** [comment]
![image](https://github.com/Gniang/RoundedTB/assets/151218278/bcd05042-af03-450c-aac6-3f37a7ffa890)
IDK but u guys need to custom this margin menu, and this is worked in my pc.

**Comment by gavtography** [comment]
>  IDK but u guys need to custom this margin menu, and this is worked in my pc.

You're a legend, this worked. I tried the fork someone made here, but it stops working after a few minutes. These settings work perfectly.

I tweaked it a little. For me these settings look the best.

![yep](https://github.com/Gniang/RoundedTB/assets/104710808/c13c0bb1-0895-4e99-bb7c-18bc834e8d0b)

Although it's pretty clear the program is still broken. Sometimes when you open certain programs, then the taskbar again hides icons. Like for me, if I open snipping tool then the taskbar is messed up again. I guess this is good enough for now. Not sure if we'll ever get a proper fix.

**Comment by ash-meta-verse** [comment]
I add ( minus - ) to the Inner Margin and it worked for me -130 was perfect 
![image](https://github.com/Gniang/RoundedTB/assets/151282206/42dcc707-d396-4288-b993-4ec23e5e348b)

**Comment by OtterKring** [comment]
Thanks, guys! The negative inner margin is working for me, too, at least until it is fixed in the code. Using Windows 11's new option to set a dark windows theme and a light app theme also fixed my issue with the transparent taskbar showing a black clock on my dark background. Now it's in readable white and with the taskbar being completely translucent I don't care how wide the margin is. 👍

**Comment by EclipsesDev** [comment]
> I add ( minus - ) to the Inner Margin and it worked for me -130 was perfect ![image](https://private-user-images.githubusercontent.com/151282206/285515553-42dcc707-d396-4288-b993-4ec23e5e348b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MDYzNDksIm5iZiI6MTcwMTQwNjA0OSwicGF0aCI6Ii8xNTEyODIyMDYvMjg1NTE1NTUzLTQyZGNjNzA3LWQzOTYtNDI4OC1iOTkzLTRlYzIzZTVlMzQ4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMVQwNDQ3MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOWIxYTFiN2Y2MDIwZmNmOTY5ODc1NWQ5NjU0OGYxMWJkNzg3YmY3YjdkMzU3N2E5ODk2OWRlN2UzYjZjNGY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cnIyMn6V7Dc2wpAPLD6hlMrGnlC7gec1Dc23YIByYUw)

alright that worked actualy in Windows 11 23H2

**Comment by 1-hyun-X-1099** [comment]
Monitoring the currently running windows works well, but there are bugs that become noticeable as those windows get deeper inside.
![스크린샷 2023-12-30 170413](https://github.com/Gniang/RoundedTB/assets/153416473/96d73917-7747-4cd9-8b35-1dbe3f0d0e82)

#

**Comment by Aboba201** [comment]
It works fine after adding the minus, but both of the top corners are square like.
![Bild_2024-01-14_123305910](https://github.com/Gniang/RoundedTB/assets/156579198/9bb5e95a-20ee-467e-9c3b-eebbd7f78d54)
(ignore the german text, i am german)

**Comment by 1111Al** [comment]
I had the same issue time ago, despite not using Windows Update for a year. I don't remember how I solved it, but the problem is not directly related to Windows updates. although these may break the program, which has been abandoned for some time now.

**Comment by PetraChristalbert** [comment]
![Screenshot 2024-05-14 201641](https://github.com/Gniang/RoundedTB/assets/151901650/d21a5c02-8342-4282-b2b6-db978b21ff8d)
Haha! This setting works totally fine with me while also including the co-pilot on the taskbar !
If you dont want the co-pilot, just make it 275, or increase it if you want to enable another taskbar default icon.

Thanks me by subs to YT : **Universal Market Service**

**Comment by AinRyzen** [comment]
The issue has been resolved. You can find the solution [here](https://github.com/Gniang/RoundedTB). If you attempted to use this version, follow these steps:

Navigate to %USERPROFILE%\APPDATA\Local.
Delete the rtb.json file, as well as another file related to RTB (I can't recall the exact name, but make sure to delete both).
After that, launch the newly downloaded RTB.
Once you've configured your settings, close the UI and then reopen the app through click the exe.
