### ISSUE TITLE
Texts are not readable

### ISSUE THREAD

**Issue by ipatavatsizz** [Gniang/RoundedTB#31]
![image](https://github.com/Gniang/RoundedTB/assets/37545799/2c06e8fb-7ab6-47c6-a166-f693389d0f74)

What should I do? I can't read anything. I just new installed and removed rtb thing.

**Comment by wuqqers** [comment]
can you fix it?

**Comment by ipatavatsizz** [comment]
Nope, after seeing some Windows-related bugs that the app caused. I removed. TransculentTB is still a goat.
