### ISSUE TITLE
Request: minimize to tray

### ISSUE THREAD

**Issue by effree** [Gniang/RoundedTB#32]
Hey i love the work you've done and the fixes to the original.

I wanted to request minimize to tray.

Right now when you minimize it minimizes to the taskbar.  But you don't want it there all the time, so you click exit, which on the original used to not exit the app but place it in the tray.  Instead now it exits the app.

So the only way to make changes, and not have it open in your taskbar is to make the changes.  Exit the app.  Then re-open the app again, which opens in the tray, and not on the taskbar.

**Comment by zanix** [comment]
You can hide the main window but it's a bit odd.
Right-click the systray icon, then "Hide RoundedTB"

**Comment by effree** [comment]
Good point, thanks

**Comment by zanix** [comment]
> Good point, thanks

Yes, but I agree that when closing the main window it should minimize to the tray and not close.
