### ISSUE TITLE
RoundedTB does not open.

### ISSUE THREAD

**Issue by Larcou** [Gniang/RoundedTB#33]
I have a 64bit laptop and roundedTB can. does not open. Even when you try to run it as an administrator.

**Comment by Larcou** [comment]
Also I have atlas os and rectify installed.

**Comment by lenvxdev** [comment]
Had the same issue, I have also AtlasOS installed.

Go to `%appdata%\Local`
then delete rtb.json and rtb.json.org 

Should fix the problem.

Source: https://github.com/Gniang/RoundedTB/issues/24

**Comment by Larcou** [comment]
Thanks
